title: Petra Šobrová
author: Petra Šobrová
email: petrasobrova10@seznam.cz
url: https://PetraSobrova.github.io
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: >
  Tourism Management undergraduate with professional experience in hospitality services, tourism operations, and event support. Specialized in guest communication, travel coordination, and high-end customer-facing environments.

permalink: /:slug.html

favicon: "icons8-disco-ball-96.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true
  lab:
    output: true
